# Generated by Django 2.2.3 on 2019-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('from_id', models.IntegerField()),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
