# Generated by Django 2.2.3 on 2019-08-05 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_logs',
            name='tele_user',
            field=models.CharField(default='Karan', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat_logs',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
