# Generated by Django 3.0 on 2019-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='ftype',
        ),
        migrations.RemoveField(
            model_name='files',
            name='path',
        ),
        migrations.AddField(
            model_name='files',
            name='media',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
