# Generated by Django 2.2.3 on 2019-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='telegram_id',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
