# Generated by Django 2.2.3 on 2019-08-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_device_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Device')),
            ],
        ),
    ]
