# Generated by Django 2.2.3 on 2019-08-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='telegram_id',
            field=models.IntegerField(default=0),
        ),
    ]
