# Generated by Django 3.0 on 2019-12-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190805_0708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
