# Generated by Django 3.0 on 2019-12-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mobile_number',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
