config_path = '/home/pi/workspace/isecrasp/config'
temp_path = '/home/pi/workspace/isecrasp/storage/temp'
dtthreads_path = '/home/pi/workspace/isecrasp/my_threads/dtexchange_thread.py'
dev_id = 'dev19765'
cred_path = '/home/pi/workspace/cred'
passwd = 'raspberry'